### ISSUE TITLE
There should be rules for EncodeFor

### ISSUE THREAD

**Issue by jmohler1970** [coldbox-modules/codechecker-core#1]
HTMLEditFormat() should suggest EncodeForHTML or EncodeForHTMLAttribute
XMLFormat() should suggest EncodeForXML or EncodeForXMLAttribute
JSStringFormat should suggest EncodeForJavascript
URLEncodedFormat() should suggest EncodeForURL

**Comment by bdw429s** [comment]
@jmohler1970 Good idea.  Would you like to send a pull request to add those rules?

**Comment by bockensm** [comment]
@jmohler1970 @bdw429s This was introduced in 1.2.0. Does the issue need to remain open or can it be closed?
