### ISSUE TITLE
Load a remote config JSON

### ISSUE THREAD

**Issue by bockensm** [coldbox-modules/codechecker-core#10]
I have many dozens of repositories that I would like to use with a single set of rules. If each repo requires its own .codechecker.json config file, it will eventually de-sync and I won't be able to run the same rules against all of these repos. For that reason, I would like to add an option to specify a remote config file instead of requiring .codechecker.json.

I have a couple ideas for implementation before I start...
1. Update the caller (commandbox-codechecker) to take a remote config URL and pass that through to codechecker-core
2. Update .codechecker.json to have a "remote" (or similar) key that points to a URL. If that key exists, the remote content will be retrieved and can be used as the config.

Looking for some feedback at this point. I think option 1 above is preferable but I don't know what impacts that would have on the codechecker app project, which I'm really not at all interested in touching since I don't use it.

**Comment by bdw429s** [comment]
@bockensm What about introducing module settings into the CLI package for all the settings in the JSON and the you can set your config "globally" into the CLI to be used for any repo you scan?  

I've never messed with this since I've always had totally different rules per repo so it never occurred to me to re-use stuff, but it could be set up as a hierarchy so each setting is
* looked for first in command params (where applicable)
* looked for next in the local JSON file (if it exists)
* defaulted to the module setting (if it exists)
This would basically leave the json stuff untouched and just add a convention of another location to read settings from.

The only decision to make then (which I deal with all the time with `server start` setting hierarchies) is whether the settings should be additive or full-overwrite.  In other words, if I configure the module globally to run rules `A` and `B` and then I also have a JSON file which is configured to run rule `C`, is the final list of rules to run `A,B,C` or just `C`?

**Comment by bockensm** [comment]
I like the idea of allowing the CLI to specify a path to a config file. Some examples:

```
codechecker run config=https://github.com/....
codechecker run config=config/.codechecker.json
```

If a URL is provided it will have to be downloaded and parsed on the fly. May be a problem, may not.

As far as the additive vs overwrite, I would defer to being consistent with what exists. If the `config` data is provided, that becomes the base config just as if a `.codechecker.json` file existed. I believe how this works is that the module has its own standard config and whatever is in the JSON config overwrites just those data points. I would like to continue with that behavior. Any CLI inputs then override both the default and any settings in the config JSON.

**Comment by bdw429s** [comment]
> I like the idea of allowing the CLI to specify a path to a config file. Some examples:

That's not a bad idea, but it really doesn't account for the scenario where a user wants to just globally default how it runs so they can simply drop themselves into any directory, run
```
codechecker run
```
and get a default defined behavior.  To be clear, this is what I was meaning
```
# one time command to set defaults
config set modules.commandbox-codechecker.excludeRules=myRuleINeverWantRun

# or perhaps this!
config set modules.commandbox-codechecker.configFile=/path/to.defaultConfig.json

# now just run it
codechecker run
```

> If a URL is provided it will have to be downloaded and parsed on the fly

Funny story, Lucee will actually do this out of the box with `fileRead( 'http://domain.com' )` but don't care for that behavior as it's a security vuln waiting to happen.  Regardless, we can do this, but I don't think it replaces my idea above really.

> As far as the additive vs overwrite, I would defer to being consistent with what exists. 

Lol, that's a non-answer because both behaviors exists where it makes sense.  For instance, if you do this
```
server set web.http.port=80
server start port=85
```
The `start` param's port will completely overwrite the port setting in the `server.json`.  But if you do this:
```
# Applies to all servers
config set server.defaults.app.libDirs=/path/to/default/jars

# applies to just this server
server set app.libDirs=/path/to/this/servers/jars

start
```
then the actual server will combine the two paths and load jars from both locations.  It boils down to what makes sense, or is the most likely scenario.  

So back to my scenario:
> if I configure the module globally to run rules A and B and then I also have a JSON file which is configured to run rule C, is the final list of rules to run A,B,C or just C?

The question becomes, would global config be defaults that a user wanted to add to (i.e., run my standard rules AND these additional rules) or only something they want used if they haven't specified anything explicitly (i.e. run these rules UNLESS I've told you to run something else entirely)

**Comment by bockensm** [comment]
All good points.

I've also realized that our needs involve custom rules from JSON files. It's not enough to have just a config JSON, but I need to bring in a handful of rule files as well. In my situation, files are broken down for logical organization, so flattening them all into a single key in the JSON config (which is already supported) is not desirable.

Maybe what would work better for me is an option to allow configuration via another module.

```
install my-codechecker-config
codechecker run config=modules/my-codechecker-config/.codechecker.json
```

That would at least get me a pathway to a shareable config as I can publish it on Forgebox and bring it in wherever it's needed.

We still have all of the same questions about which rules trump which. You're suggesting that we can potentially configure the module in the following ways:
* global configs ( e.g. `config set modules.commandbox-codechecker.configFile=/path/to.defaultConfig.json` )
* specific config via file ( e.g. `codechecker run config=config.json` )
* config implicitly ( e.g. `codechecker run`, assuming no global configs )
* default module config ( e.g. `codechecker run`, assuming no global config and no CLI config or .codechecker.json file )

Yes, that's a lot to handle. I consider the global config outside the scope of what I'm trying to pull off here. That's not to say it's not valuable, but I would tackle that separately. The only layer I'm hoping to add is to be able to move from a requirement where the config file has to be `.codechecker.json` to allow me to specify an alternate path. All of the same rules could then apply in terms of what overwrites what. If the config precedence needs to be modified, then that's also a separate task, in my opinion.

Now that we've talked me off of the remote config ledge, may I suggest that the module be extended to take a CLI arg for where the config file can be found? That's the only change I would need at this time.

For what it's worth, my answer of what to do in the case of both global and CLI config being present is I'd let the CLI fully overwrite whatever the global config is. It's a bit like an environment variable being declared in `/etc/environment` and then redeclared on the command line immediately prior to execution of a script. Granted, that example doesn't consider what could be a list or array of items, but that's my opinion.

**Comment by bdw429s** [comment]
@bockensm I think just being able to specify the name of the default config file is a good start and super simple.  Update your system modules and tell me if what I just committed works for you.  It supports the following:
```
codechecker run configPath=/dir/to/config
codechecker run configPath=/dir/to/config/file.json
codechecker run configPath=https://domain.com/static/config.json
```

The first line would still look for a file called `.codechecker.json`, it would just let you override the default directory where it looks.

**Comment by bockensm** [comment]
My intention is to have a module that is self-contained and includes `.codechecker.json` and any rule definitions. I attached a trivial ZIP file that shows how I figured I might set this up.

[codechecker.zip](https://github.com/coldbox-modules/codechecker-core/files/8218510/codechecker.zip)

`codechecker run configPath=modules/code-standards/`
Finds the custom rule file just fine and scans the one .cfm file I have, but doesn't report that there's an issue. I'm hoping that I'm just dense and made a rookie mistake.

`codechecker run configPath=modules/code-standards/.codechecker.json`
Not able to find the rule files. I tried `./rules/modern.json` and `rules/modern.json`, neither works. It's looking for the file here:
`modules\code-standards\.codechecker.json\rules\modern.json`

`codechecker run configPath=https://domain.com/static/config.json`
Not tested since I have accompanying custom rules.

**Comment by bdw429s** [comment]
Hmm, both of those work fine for me just as a relative file path.  I just tested this:

```
echo {} > modules/code-standards/foo.json
codechecker run configPath=modules/code-standards/foo.json

echo {} > modules/code-standards/.codechecker.json
codechecker run configPath=modules/code-standards/
```

Both of those examples find the file and run.  Are you sure you're running the latest module and are you sure The `modules/code-standards/` path exists relative to where you are running the command?

**Comment by bockensm** [comment]
commandbox-codechecker is on v1.3.3. I am running all commands from `/home/mark/commandbox`.

This will throw an error:
```
$ echo '{ "ruleFiles": [ "custom.json" ] }' > modules/code-standards/.codechecker.json
$ echo [] > modules/code-standards/custom.json
$ codechecker run configpath=modules/code-standards/.codechecker.json

Rule file not found.

/home/mark/commandbox/modules/code-standards/.codechecker.json/custom.json
```

Even if I use something like `config.json` in place of `.codechecker.json`, I get the same error.

This will run properly:
```
$ echo '{ "ruleFiles": [ "custom.json" ] }' > modules/code-standards/.codechecker.json
$ echo [] > modules/code-standards/custom.json
$ codechecker run configpath=modules/code-standards/
```

The only difference is that I did not specify a JSON file in `configPath` and left it at a directory. 

This also runs without error, indicating that the rule file can be found even if it's in a child directory.
```
$ echo '{ "ruleFiles": [ "rules/custom.json" ] }' > modules/code-standards/.codechecker.json
$ mkdir modules/code-standards/rules
$ echo [] > modules/code-standards/rules/custom.json
$ codechecker run configpath=modules/code-standards/
```

**Comment by bdw429s** [comment]
Ah, ok-- I completely misunderstood you.  I thought you were saying the `.codechecker.json` files wasn't found-- I see now you means the RULES JSON file wasn't found.  Yes, this is a very simple fix-- I just need to use `getDirectoryFromPath()` to find the folder the code checker JSON.  Try again on the new version I just pushed.

**Comment by bockensm** [comment]
I can confirm that both run and are able to locate the rule files I provided using the following versions:
commandbox-codechecker 1.3.3
codechecker-core 1.3.1

I'm happy for this to be closed at this point.

**Comment by bdw429s** [comment]
Sweet-- I think we had a lot of other cool ideas here, but we can spin up separate tickets later for those.  Glad we've got something that gets you farther down the road.
