### ISSUE TITLE
Case sensitive checking function

### ISSUE THREAD

**Issue by bockensm** [coldbox-modules/codechecker-core#11]
I find myself needing a way to write case-sensitive regex rules. Currently, `checkCode` does not care about case. If I were after case-sensitive support, would it make the most sense to copy `checkCode` to another function called `checkCodeCaseSensitive` and then declare that as my "functionname" in rules where I need the sensitivity? This would be achieveable without changing too much of how arguments are passed along to the checking functions.

Example:
```json
{
	"pattern": "cfoutput",
	"message": "CFoutput is lame",
	"category": "One-off Rules",
	"name": "Don't use CFoutput",
	"extensions": "cfm,cfc",
	"severity": "3",
        "functionname": "checkCodeCaseSensitive"
}
```

Option 2 is to add another key to each rule definition for "caseSensitive" with an implied value of false. Then I could do this:
```json
{
	"pattern": "cfoutput",
	"message": "CFoutput is lame",
	"category": "One-off Rules",
	"name": "Don't use CFoutput",
	"extensions": "cfm,cfc",
	"severity": "3",
        "caseSensitive" true
}
```

The value of "caseSensitive" will have to be passed along whenever line, passonmatch, and pattern are passed. The called function, if any (I can't find any), would also need to be updated to support the new argument.

**Comment by bdw429s** [comment]
I think we'd want to do
```
 "caseSensitive" true
```
and default it to `false`.  Then internally, swap out whether we call `reFind()` or `reFindNoCase()`

**Comment by bdw429s** [comment]
Sorry, this one completely missed my radar.
