### ISSUE TITLE
Support negative path globbing

### ISSUE THREAD

**Issue by bockensm** [coldbox-modules/codechecker-core#7]
Let's say I have a path `components/**.cf?` but I want to exclude `components/libs/*`, I need to be able to do that instead of listing all of the other subfolders of components.

In this case, I'd want something like this:
```json
{
  "paths": "components/**.cf?,!components/lib/*"
}
```

Motivation for this came from gulp-eslint: `gulp.src(['**/*.js','!node_modules/**'])`

_(Marking this as an issue so I can work on it later... maybe)_

**Comment by bdw429s** [comment]
@bockensm I actually made changes to the CommandBox globbing library in the 5.0 version of CommandBox specifically with the codechecker in mind.

* globber library accepts more than one globbing whitelist pattern
* globber library accepts excludes (blacklist) patterns as well now

https://commandbox.ortusbooks.com/developing-for-commandbox/commands/using-parameters/using-file-globs#exclude-patterns

Codechecker just needs updated to take advantage of this (and possible rework the existing logic that mimics the multiple whitelist functionality) and then we'd need to decide how to handle backwards compat with versions of CommandBox that doesn't support these new features.

**Comment by bdw429s** [comment]
Also, another quick note, this is the repo for the codechecker core.  The changes I was talking about above would be in the https://github.com/commandbox-modules/commandbox-codechecker repo which actually has the CLI implementation.  The core doesn't actually do anything with the globbing patterns as the CLI does all the work of building the list of the files to check and then it just passes them to the core one at a time for processing.

**Comment by bockensm** [comment]
Yea, you're right. I have the wrong repo.
